
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: repa
      POSTGRES_USER: repa_user
      POSTGRES_PASSWORD: repa_pass
    ports:
      - "5432:5432"
    volumes:
      - repa_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  repa_pg_data: